// Package ci renders the files `ovc init` puts at the root of every schema
// branch: ovc.yaml and the CI entry points for GitHub Actions and GitLab CI
// (spec §5.4, §10.2).
package ci

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// Settings come from the server config (§13.1).
type Settings struct {
	GitHubTemplate string // e.g. org/ovc-ci-templates/.github/workflows/oracle-deploy.yml@v1
	GitLabProject  string // e.g. db/ovc-ci-templates
	GitLabFile     string // e.g. /oracle-deploy.yml
}

// DefaultExclude is the object filter of spec §5.4.
var DefaultExclude = []string{"SYS_*", "BIN$*", "MLOG$_*", "RUPD$_*", "TMP_*"}

type ovcYAML struct {
	Schema  string `yaml:"schema"`
	Version int    `yaml:"version"`
	Deploy  struct {
		AllowDrop        bool `yaml:"allow_drop"`
		Recompile        bool `yaml:"recompile"`
		FailOnNewInvalid bool `yaml:"fail_on_new_invalid"`
	} `yaml:"deploy"`
	Exclude []string `yaml:"exclude"`
	Sync    struct {
		AutoSync bool     `yaml:"auto_sync"`
		Envs     []string `yaml:"envs"`
	} `yaml:"sync"`
}

// OvcYAML renders ovc.yaml with the defaults of spec §5.4.
func OvcYAML(schema string, exclude, envs []string) ([]byte, error) {
	var y ovcYAML
	y.Schema, y.Version = schema, 1
	y.Deploy.Recompile, y.Deploy.FailOnNewInvalid = true, true
	y.Exclude = exclude
	y.Sync.Envs = envs
	return yaml.Marshal(y)
}

var githubTmpl = template.Must(template.New("gh").Parse(`# Generated by ovc init. The real pipeline lives in the shared template.
name: ovc-deploy
on:
  push:
    branches: [{{.Branches}}]
  pull_request:
    branches: [{{.Branches}}]
jobs:
  ovc:
    uses: {{.Template}}
    secrets: inherit
`))

var gitlabTmpl = template.Must(template.New("gl").Parse(`# Generated by ovc init. The real pipeline lives in the shared template.
include:
  - project: {{.Project}}
    file: {{.File}}
`))

// Files returns the repo-relative path -> content of every CI file. With no
// template configured at all it returns none (a repo used only to try OVC out);
// configuring just one of the two is an error.
func Files(s Settings, envs []string) (map[string][]byte, error) {
	if s.GitHubTemplate == "" && s.GitLabProject == "" {
		return map[string][]byte{}, nil
	}
	if s.GitHubTemplate == "" || s.GitLabProject == "" {
		return nil, fmt.Errorf("ci: github_template and gitlab_project must be configured together")
	}
	if s.GitLabFile == "" {
		s.GitLabFile = "/oracle-deploy.yml"
	}
	pats := make([]string, len(envs))
	for i, e := range envs {
		pats[i] = fmt.Sprintf("%q", e) // one branch per database (spec §10.2)
	}
	var gh, gl bytes.Buffer
	if err := githubTmpl.Execute(&gh, map[string]string{"Branches": strings.Join(pats, ", "), "Template": s.GitHubTemplate}); err != nil {
		return nil, err
	}
	if err := gitlabTmpl.Execute(&gl, map[string]string{"Project": s.GitLabProject, "File": s.GitLabFile}); err != nil {
		return nil, err
	}
	return map[string][]byte{
		".github/workflows/ovc-deploy.yml": gh.Bytes(),
		".gitlab-ci.yml":                   gl.Bytes(),
	}, nil
}
