-- Fixture for local integration tests (not for real databases).
-- usage: sqlplus sys@//host/FREEPDB1 as sysdba @fixture.sql <hr_pw> <reader_pw>
WHENEVER SQLERROR EXIT FAILURE
DEFINE hr_pw = &1
DEFINE reader_pw = &2

CREATE USER HR IDENTIFIED BY "&hr_pw" QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE,
      CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM, CREATE MATERIALIZED VIEW TO HR;
CREATE USER OVC_READER IDENTIFIED BY "&reader_pw";
GRANT CREATE SESSION, SELECT ANY DICTIONARY, SELECT_CATALOG_ROLE TO OVC_READER;

CREATE TABLE HR.DEPARTMENTS (ID NUMBER PRIMARY KEY, NAME VARCHAR2(100) NOT NULL);
CREATE TABLE HR.EMPLOYEES (
  ID NUMBER PRIMARY KEY, NAME VARCHAR2(100), EMAIL VARCHAR2(200), SALARY NUMBER,
  DEPT_ID NUMBER, CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES HR.DEPARTMENTS(ID));
CREATE SEQUENCE HR.EMPLOYEES_SEQ;
CREATE INDEX HR.EMPLOYEES_IX1 ON HR.EMPLOYEES(NAME);
CREATE OR REPLACE VIEW HR.V_EMPLOYEE_INFO AS SELECT ID, NAME FROM HR.EMPLOYEES;
CREATE MATERIALIZED VIEW HR.MV_EMP_COUNT AS SELECT COUNT(*) CNT FROM HR.EMPLOYEES;
CREATE OR REPLACE TYPE HR.T_EMP_REC AS OBJECT (id NUMBER, name VARCHAR2(100));
/
CREATE OR REPLACE PACKAGE HR.PKG_EMPLOYEE AS
  PROCEDURE add_emp(p_name VARCHAR2);
  FUNCTION cnt RETURN NUMBER;
END PKG_EMPLOYEE;
/
CREATE OR REPLACE PACKAGE BODY HR.PKG_EMPLOYEE AS
  PROCEDURE add_emp(p_name VARCHAR2) IS BEGIN INSERT INTO HR.EMPLOYEES(ID,NAME) VALUES (HR.EMPLOYEES_SEQ.NEXTVAL,p_name); END;
  FUNCTION cnt RETURN NUMBER IS n NUMBER; BEGIN SELECT COUNT(*) INTO n FROM HR.EMPLOYEES; RETURN n; END;
END PKG_EMPLOYEE;
/
CREATE OR REPLACE PROCEDURE HR.P_SYNC_EMPLOYEE IS BEGIN NULL; END;
/
CREATE OR REPLACE FUNCTION HR.F_GET_SALARY(p_id NUMBER) RETURN NUMBER IS BEGIN RETURN 1; END;
/
CREATE OR REPLACE TRIGGER HR.TRG_EMPLOYEES_BIU BEFORE INSERT OR UPDATE ON HR.EMPLOYEES FOR EACH ROW BEGIN :NEW.EMAIL := LOWER(:NEW.EMAIL); END;
/
CREATE OR REPLACE SYNONYM HR.SYN_DEPT FOR HR.DEPARTMENTS;
CREATE TABLE HR.TMP_SCRATCH (X NUMBER);
EXIT
